/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdjustStockArgs {
  'note' : [] | [string],
  'productId' : ProductId,
  'quantity' : bigint,
  'adjustmentType' : AdjustmentType,
}
export type AdjustmentType = { 'remove' : null } |
  { 'return' : null } |
  { 'damage' : null } |
  { 'recount' : null } |
  { 'sale' : null } |
  { 'receivedFromPO' : null } |
  { 'restock' : null };
export interface CategorySummary {
  'totalValue' : bigint,
  'productCount' : bigint,
  'category' : string,
}
export interface CreatePOArgs {
  'lineItems' : Array<CreatePOLineItemArgs>,
  'expectedDeliveryDate' : [] | [bigint],
  'supplierName' : string,
  'notes' : [] | [string],
  'supplierId' : SupplierId,
}
export interface CreatePOLineItemArgs {
  'orderedQty' : bigint,
  'productId' : ProductId,
  'unitCostPrice' : bigint,
}
export interface CreateProductArgs {
  'sku' : string,
  'unitOfMeasure' : string,
  'lowStockThreshold' : [] | [bigint],
  'name' : string,
  'reorderQuantity' : bigint,
  'sellingPrice' : bigint,
  'description' : string,
  'barcode' : [] | [string],
  'quantity' : bigint,
  'category' : string,
  'price' : bigint,
  'costPrice' : bigint,
  'supplierId' : [] | [SupplierId],
}
export interface CreateSupplierArgs {
  'name' : string,
  'contactPerson' : string,
  'isActive' : boolean,
  'email' : string,
  'address' : string,
  'paymentTerms' : string,
  'phone' : string,
}
export interface DashboardMetrics {
  'categories' : Array<CategorySummary>,
  'totalProducts' : bigint,
  'pendingPOValue' : bigint,
  'totalInventoryValue' : bigint,
  'pendingPOCount' : bigint,
  'lowStockCount' : bigint,
  'lowStockProducts' : Array<LowStockSummary>,
}
export interface LowStockSummary {
  'id' : ProductId,
  'sku' : string,
  'reorderPoint' : bigint,
  'name' : string,
  'currentStock' : bigint,
}
export type POId = bigint;
export interface POLineItem {
  'receivedQty' : bigint,
  'orderedQty' : bigint,
  'productSku' : string,
  'productId' : ProductId,
  'productName' : string,
  'unitCostPrice' : bigint,
}
export type POStatus = { 'cancelled' : null } |
  { 'sent' : null } |
  { 'partiallyReceived' : null } |
  { 'draft' : null } |
  { 'received' : null };
export interface Product {
  'id' : ProductId,
  'sku' : string,
  'unitOfMeasure' : string,
  'lowStockThreshold' : [] | [bigint],
  'stockStatus' : StockStatus,
  'name' : string,
  'reorderQuantity' : bigint,
  'sellingPrice' : bigint,
  'description' : string,
  'lastModified' : Timestamp,
  'barcode' : [] | [string],
  'quantity' : bigint,
  'category' : string,
  'price' : bigint,
  'costPrice' : bigint,
  'supplierId' : [] | [SupplierId],
}
export type ProductId = bigint;
export interface PurchaseOrder {
  'id' : POId,
  'status' : POStatus,
  'lineItems' : Array<POLineItem>,
  'expectedDeliveryDate' : [] | [bigint],
  'supplierName' : string,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'totalAmount' : bigint,
  'notes' : [] | [string],
  'supplierId' : SupplierId,
}
export interface ReceiveItemArgs {
  'receivedQty' : bigint,
  'productId' : ProductId,
}
export interface SearchFilterArgs {
  'sortField' : [] | [SortField],
  'stockStatus' : [] | [StockStatus],
  'sortOrder' : [] | [SortOrder],
  'searchQuery' : [] | [string],
  'supplierId' : [] | [SupplierId],
}
export type SortField = { 'sku' : null } |
  { 'name' : null } |
  { 'lastModified' : null } |
  { 'quantity' : null } |
  { 'price' : null };
export type SortOrder = { 'asc' : null } |
  { 'desc' : null };
export interface StockHistoryEntry {
  'id' : bigint,
  'note' : [] | [string],
  'productId' : ProductId,
  'notes' : [] | [string],
  'timestamp' : Timestamp,
  'quantity' : bigint,
  'adjustmentType' : AdjustmentType,
}
export type StockStatus = { 'inStock' : null } |
  { 'outOfStock' : null } |
  { 'lowStock' : null };
export interface Supplier {
  'id' : SupplierId,
  'name' : string,
  'createdAt' : Timestamp,
  'contactPerson' : string,
  'isActive' : boolean,
  'email' : string,
  'address' : string,
  'paymentTerms' : string,
  'phone' : string,
}
export type SupplierId = bigint;
export type Timestamp = bigint;
export interface UpdatePOStatusArgs { 'id' : POId, 'status' : POStatus }
export interface UpdateProductArgs {
  'id' : ProductId,
  'sku' : string,
  'unitOfMeasure' : string,
  'lowStockThreshold' : [] | [bigint],
  'name' : string,
  'reorderQuantity' : bigint,
  'sellingPrice' : bigint,
  'description' : string,
  'barcode' : [] | [string],
  'category' : string,
  'price' : bigint,
  'costPrice' : bigint,
  'supplierId' : [] | [SupplierId],
}
export interface UpdateSupplierArgs {
  'name' : [] | [string],
  'contactPerson' : [] | [string],
  'isActive' : [] | [boolean],
  'email' : [] | [string],
  'address' : [] | [string],
  'paymentTerms' : [] | [string],
  'phone' : [] | [string],
}
export interface _SERVICE {
  'adjustStock' : ActorMethod<
    [AdjustStockArgs],
    { 'ok' : Product } |
      { 'err' : string }
  >,
  'cancelPO' : ActorMethod<[POId], [] | [PurchaseOrder]>,
  'createPO' : ActorMethod<[CreatePOArgs], PurchaseOrder>,
  'createProduct' : ActorMethod<
    [CreateProductArgs],
    { 'ok' : Product } |
      { 'err' : string }
  >,
  'createSupplier' : ActorMethod<[CreateSupplierArgs], Supplier>,
  'deleteProduct' : ActorMethod<
    [ProductId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteSupplier' : ActorMethod<[SupplierId], boolean>,
  'getDashboardMetrics' : ActorMethod<[], DashboardMetrics>,
  'getGlobalLowStockThreshold' : ActorMethod<[], bigint>,
  'getPO' : ActorMethod<[POId], [] | [PurchaseOrder]>,
  'getPOsBySupplier' : ActorMethod<[SupplierId], Array<PurchaseOrder>>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getStockHistory' : ActorMethod<[[] | [ProductId]], Array<StockHistoryEntry>>,
  'getSupplier' : ActorMethod<[SupplierId], [] | [Supplier]>,
  'getSupplierProducts' : ActorMethod<[SupplierId], Array<ProductId>>,
  'listPOs' : ActorMethod<[[] | [POStatus]], Array<PurchaseOrder>>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'listSuppliers' : ActorMethod<[[] | [boolean]], Array<Supplier>>,
  'receivePO' : ActorMethod<
    [POId, Array<ReceiveItemArgs>],
    [] | [PurchaseOrder]
  >,
  'searchProducts' : ActorMethod<[SearchFilterArgs], Array<Product>>,
  'setGlobalLowStockThreshold' : ActorMethod<[bigint], undefined>,
  'updatePOStatus' : ActorMethod<[UpdatePOStatusArgs], [] | [PurchaseOrder]>,
  'updateProduct' : ActorMethod<
    [UpdateProductArgs],
    { 'ok' : Product } |
      { 'err' : string }
  >,
  'updateSupplier' : ActorMethod<
    [SupplierId, UpdateSupplierArgs],
    [] | [Supplier]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];