/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Nat;
export const AdjustmentType = IDL.Variant({
  'remove' : IDL.Null,
  'return' : IDL.Null,
  'damage' : IDL.Null,
  'recount' : IDL.Null,
  'sale' : IDL.Null,
  'receivedFromPO' : IDL.Null,
  'restock' : IDL.Null,
});
export const AdjustStockArgs = IDL.Record({
  'note' : IDL.Opt(IDL.Text),
  'productId' : ProductId,
  'quantity' : IDL.Nat,
  'adjustmentType' : AdjustmentType,
});
export const StockStatus = IDL.Variant({
  'inStock' : IDL.Null,
  'outOfStock' : IDL.Null,
  'lowStock' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const SupplierId = IDL.Nat;
export const Product = IDL.Record({
  'id' : ProductId,
  'sku' : IDL.Text,
  'unitOfMeasure' : IDL.Text,
  'lowStockThreshold' : IDL.Opt(IDL.Nat),
  'stockStatus' : StockStatus,
  'name' : IDL.Text,
  'reorderQuantity' : IDL.Nat,
  'sellingPrice' : IDL.Nat,
  'description' : IDL.Text,
  'lastModified' : Timestamp,
  'barcode' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'costPrice' : IDL.Nat,
  'supplierId' : IDL.Opt(SupplierId),
});
export const POId = IDL.Nat;
export const POStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'sent' : IDL.Null,
  'partiallyReceived' : IDL.Null,
  'draft' : IDL.Null,
  'received' : IDL.Null,
});
export const POLineItem = IDL.Record({
  'receivedQty' : IDL.Nat,
  'orderedQty' : IDL.Nat,
  'productSku' : IDL.Text,
  'productId' : ProductId,
  'productName' : IDL.Text,
  'unitCostPrice' : IDL.Nat,
});
export const PurchaseOrder = IDL.Record({
  'id' : POId,
  'status' : POStatus,
  'lineItems' : IDL.Vec(POLineItem),
  'expectedDeliveryDate' : IDL.Opt(IDL.Int),
  'supplierName' : IDL.Text,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'totalAmount' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
  'supplierId' : SupplierId,
});
export const CreatePOLineItemArgs = IDL.Record({
  'orderedQty' : IDL.Nat,
  'productId' : ProductId,
  'unitCostPrice' : IDL.Nat,
});
export const CreatePOArgs = IDL.Record({
  'lineItems' : IDL.Vec(CreatePOLineItemArgs),
  'expectedDeliveryDate' : IDL.Opt(IDL.Int),
  'supplierName' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'supplierId' : SupplierId,
});
export const CreateProductArgs = IDL.Record({
  'sku' : IDL.Text,
  'unitOfMeasure' : IDL.Text,
  'lowStockThreshold' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'reorderQuantity' : IDL.Nat,
  'sellingPrice' : IDL.Nat,
  'description' : IDL.Text,
  'barcode' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'costPrice' : IDL.Nat,
  'supplierId' : IDL.Opt(SupplierId),
});
export const CreateSupplierArgs = IDL.Record({
  'name' : IDL.Text,
  'contactPerson' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'paymentTerms' : IDL.Text,
  'phone' : IDL.Text,
});
export const Supplier = IDL.Record({
  'id' : SupplierId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'contactPerson' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'paymentTerms' : IDL.Text,
  'phone' : IDL.Text,
});
export const CategorySummary = IDL.Record({
  'totalValue' : IDL.Nat,
  'productCount' : IDL.Nat,
  'category' : IDL.Text,
});
export const LowStockSummary = IDL.Record({
  'id' : ProductId,
  'sku' : IDL.Text,
  'reorderPoint' : IDL.Nat,
  'name' : IDL.Text,
  'currentStock' : IDL.Nat,
});
export const DashboardMetrics = IDL.Record({
  'categories' : IDL.Vec(CategorySummary),
  'totalProducts' : IDL.Nat,
  'pendingPOValue' : IDL.Nat,
  'totalInventoryValue' : IDL.Nat,
  'pendingPOCount' : IDL.Nat,
  'lowStockCount' : IDL.Nat,
  'lowStockProducts' : IDL.Vec(LowStockSummary),
});
export const StockHistoryEntry = IDL.Record({
  'id' : IDL.Nat,
  'note' : IDL.Opt(IDL.Text),
  'productId' : ProductId,
  'notes' : IDL.Opt(IDL.Text),
  'timestamp' : Timestamp,
  'quantity' : IDL.Nat,
  'adjustmentType' : AdjustmentType,
});
export const ReceiveItemArgs = IDL.Record({
  'receivedQty' : IDL.Nat,
  'productId' : ProductId,
});
export const SortField = IDL.Variant({
  'sku' : IDL.Null,
  'name' : IDL.Null,
  'lastModified' : IDL.Null,
  'quantity' : IDL.Null,
  'price' : IDL.Null,
});
export const SortOrder = IDL.Variant({ 'asc' : IDL.Null, 'desc' : IDL.Null });
export const SearchFilterArgs = IDL.Record({
  'sortField' : IDL.Opt(SortField),
  'stockStatus' : IDL.Opt(StockStatus),
  'sortOrder' : IDL.Opt(SortOrder),
  'searchQuery' : IDL.Opt(IDL.Text),
  'supplierId' : IDL.Opt(SupplierId),
});
export const UpdatePOStatusArgs = IDL.Record({
  'id' : POId,
  'status' : POStatus,
});
export const UpdateProductArgs = IDL.Record({
  'id' : ProductId,
  'sku' : IDL.Text,
  'unitOfMeasure' : IDL.Text,
  'lowStockThreshold' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'reorderQuantity' : IDL.Nat,
  'sellingPrice' : IDL.Nat,
  'description' : IDL.Text,
  'barcode' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'costPrice' : IDL.Nat,
  'supplierId' : IDL.Opt(SupplierId),
});
export const UpdateSupplierArgs = IDL.Record({
  'name' : IDL.Opt(IDL.Text),
  'contactPerson' : IDL.Opt(IDL.Text),
  'isActive' : IDL.Opt(IDL.Bool),
  'email' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'paymentTerms' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'adjustStock' : IDL.Func(
      [AdjustStockArgs],
      [IDL.Variant({ 'ok' : Product, 'err' : IDL.Text })],
      [],
    ),
  'cancelPO' : IDL.Func([POId], [IDL.Opt(PurchaseOrder)], []),
  'createPO' : IDL.Func([CreatePOArgs], [PurchaseOrder], []),
  'createProduct' : IDL.Func(
      [CreateProductArgs],
      [IDL.Variant({ 'ok' : Product, 'err' : IDL.Text })],
      [],
    ),
  'createSupplier' : IDL.Func([CreateSupplierArgs], [Supplier], []),
  'deleteProduct' : IDL.Func(
      [ProductId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteSupplier' : IDL.Func([SupplierId], [IDL.Bool], []),
  'getDashboardMetrics' : IDL.Func([], [DashboardMetrics], ['query']),
  'getGlobalLowStockThreshold' : IDL.Func([], [IDL.Nat], ['query']),
  'getPO' : IDL.Func([POId], [IDL.Opt(PurchaseOrder)], ['query']),
  'getPOsBySupplier' : IDL.Func(
      [SupplierId],
      [IDL.Vec(PurchaseOrder)],
      ['query'],
    ),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getStockHistory' : IDL.Func(
      [IDL.Opt(ProductId)],
      [IDL.Vec(StockHistoryEntry)],
      ['query'],
    ),
  'getSupplier' : IDL.Func([SupplierId], [IDL.Opt(Supplier)], ['query']),
  'getSupplierProducts' : IDL.Func(
      [SupplierId],
      [IDL.Vec(ProductId)],
      ['query'],
    ),
  'listPOs' : IDL.Func(
      [IDL.Opt(POStatus)],
      [IDL.Vec(PurchaseOrder)],
      ['query'],
    ),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listSuppliers' : IDL.Func(
      [IDL.Opt(IDL.Bool)],
      [IDL.Vec(Supplier)],
      ['query'],
    ),
  'receivePO' : IDL.Func(
      [POId, IDL.Vec(ReceiveItemArgs)],
      [IDL.Opt(PurchaseOrder)],
      [],
    ),
  'searchProducts' : IDL.Func(
      [SearchFilterArgs],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'setGlobalLowStockThreshold' : IDL.Func([IDL.Nat], [], []),
  'updatePOStatus' : IDL.Func(
      [UpdatePOStatusArgs],
      [IDL.Opt(PurchaseOrder)],
      [],
    ),
  'updateProduct' : IDL.Func(
      [UpdateProductArgs],
      [IDL.Variant({ 'ok' : Product, 'err' : IDL.Text })],
      [],
    ),
  'updateSupplier' : IDL.Func(
      [SupplierId, UpdateSupplierArgs],
      [IDL.Opt(Supplier)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Nat;
  const AdjustmentType = IDL.Variant({
    'remove' : IDL.Null,
    'return' : IDL.Null,
    'damage' : IDL.Null,
    'recount' : IDL.Null,
    'sale' : IDL.Null,
    'receivedFromPO' : IDL.Null,
    'restock' : IDL.Null,
  });
  const AdjustStockArgs = IDL.Record({
    'note' : IDL.Opt(IDL.Text),
    'productId' : ProductId,
    'quantity' : IDL.Nat,
    'adjustmentType' : AdjustmentType,
  });
  const StockStatus = IDL.Variant({
    'inStock' : IDL.Null,
    'outOfStock' : IDL.Null,
    'lowStock' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const SupplierId = IDL.Nat;
  const Product = IDL.Record({
    'id' : ProductId,
    'sku' : IDL.Text,
    'unitOfMeasure' : IDL.Text,
    'lowStockThreshold' : IDL.Opt(IDL.Nat),
    'stockStatus' : StockStatus,
    'name' : IDL.Text,
    'reorderQuantity' : IDL.Nat,
    'sellingPrice' : IDL.Nat,
    'description' : IDL.Text,
    'lastModified' : Timestamp,
    'barcode' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'costPrice' : IDL.Nat,
    'supplierId' : IDL.Opt(SupplierId),
  });
  const POId = IDL.Nat;
  const POStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'sent' : IDL.Null,
    'partiallyReceived' : IDL.Null,
    'draft' : IDL.Null,
    'received' : IDL.Null,
  });
  const POLineItem = IDL.Record({
    'receivedQty' : IDL.Nat,
    'orderedQty' : IDL.Nat,
    'productSku' : IDL.Text,
    'productId' : ProductId,
    'productName' : IDL.Text,
    'unitCostPrice' : IDL.Nat,
  });
  const PurchaseOrder = IDL.Record({
    'id' : POId,
    'status' : POStatus,
    'lineItems' : IDL.Vec(POLineItem),
    'expectedDeliveryDate' : IDL.Opt(IDL.Int),
    'supplierName' : IDL.Text,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'totalAmount' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
    'supplierId' : SupplierId,
  });
  const CreatePOLineItemArgs = IDL.Record({
    'orderedQty' : IDL.Nat,
    'productId' : ProductId,
    'unitCostPrice' : IDL.Nat,
  });
  const CreatePOArgs = IDL.Record({
    'lineItems' : IDL.Vec(CreatePOLineItemArgs),
    'expectedDeliveryDate' : IDL.Opt(IDL.Int),
    'supplierName' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'supplierId' : SupplierId,
  });
  const CreateProductArgs = IDL.Record({
    'sku' : IDL.Text,
    'unitOfMeasure' : IDL.Text,
    'lowStockThreshold' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'reorderQuantity' : IDL.Nat,
    'sellingPrice' : IDL.Nat,
    'description' : IDL.Text,
    'barcode' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'costPrice' : IDL.Nat,
    'supplierId' : IDL.Opt(SupplierId),
  });
  const CreateSupplierArgs = IDL.Record({
    'name' : IDL.Text,
    'contactPerson' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'paymentTerms' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Supplier = IDL.Record({
    'id' : SupplierId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'contactPerson' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'paymentTerms' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CategorySummary = IDL.Record({
    'totalValue' : IDL.Nat,
    'productCount' : IDL.Nat,
    'category' : IDL.Text,
  });
  const LowStockSummary = IDL.Record({
    'id' : ProductId,
    'sku' : IDL.Text,
    'reorderPoint' : IDL.Nat,
    'name' : IDL.Text,
    'currentStock' : IDL.Nat,
  });
  const DashboardMetrics = IDL.Record({
    'categories' : IDL.Vec(CategorySummary),
    'totalProducts' : IDL.Nat,
    'pendingPOValue' : IDL.Nat,
    'totalInventoryValue' : IDL.Nat,
    'pendingPOCount' : IDL.Nat,
    'lowStockCount' : IDL.Nat,
    'lowStockProducts' : IDL.Vec(LowStockSummary),
  });
  const StockHistoryEntry = IDL.Record({
    'id' : IDL.Nat,
    'note' : IDL.Opt(IDL.Text),
    'productId' : ProductId,
    'notes' : IDL.Opt(IDL.Text),
    'timestamp' : Timestamp,
    'quantity' : IDL.Nat,
    'adjustmentType' : AdjustmentType,
  });
  const ReceiveItemArgs = IDL.Record({
    'receivedQty' : IDL.Nat,
    'productId' : ProductId,
  });
  const SortField = IDL.Variant({
    'sku' : IDL.Null,
    'name' : IDL.Null,
    'lastModified' : IDL.Null,
    'quantity' : IDL.Null,
    'price' : IDL.Null,
  });
  const SortOrder = IDL.Variant({ 'asc' : IDL.Null, 'desc' : IDL.Null });
  const SearchFilterArgs = IDL.Record({
    'sortField' : IDL.Opt(SortField),
    'stockStatus' : IDL.Opt(StockStatus),
    'sortOrder' : IDL.Opt(SortOrder),
    'searchQuery' : IDL.Opt(IDL.Text),
    'supplierId' : IDL.Opt(SupplierId),
  });
  const UpdatePOStatusArgs = IDL.Record({ 'id' : POId, 'status' : POStatus });
  const UpdateProductArgs = IDL.Record({
    'id' : ProductId,
    'sku' : IDL.Text,
    'unitOfMeasure' : IDL.Text,
    'lowStockThreshold' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'reorderQuantity' : IDL.Nat,
    'sellingPrice' : IDL.Nat,
    'description' : IDL.Text,
    'barcode' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'costPrice' : IDL.Nat,
    'supplierId' : IDL.Opt(SupplierId),
  });
  const UpdateSupplierArgs = IDL.Record({
    'name' : IDL.Opt(IDL.Text),
    'contactPerson' : IDL.Opt(IDL.Text),
    'isActive' : IDL.Opt(IDL.Bool),
    'email' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'paymentTerms' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'adjustStock' : IDL.Func(
        [AdjustStockArgs],
        [IDL.Variant({ 'ok' : Product, 'err' : IDL.Text })],
        [],
      ),
    'cancelPO' : IDL.Func([POId], [IDL.Opt(PurchaseOrder)], []),
    'createPO' : IDL.Func([CreatePOArgs], [PurchaseOrder], []),
    'createProduct' : IDL.Func(
        [CreateProductArgs],
        [IDL.Variant({ 'ok' : Product, 'err' : IDL.Text })],
        [],
      ),
    'createSupplier' : IDL.Func([CreateSupplierArgs], [Supplier], []),
    'deleteProduct' : IDL.Func(
        [ProductId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteSupplier' : IDL.Func([SupplierId], [IDL.Bool], []),
    'getDashboardMetrics' : IDL.Func([], [DashboardMetrics], ['query']),
    'getGlobalLowStockThreshold' : IDL.Func([], [IDL.Nat], ['query']),
    'getPO' : IDL.Func([POId], [IDL.Opt(PurchaseOrder)], ['query']),
    'getPOsBySupplier' : IDL.Func(
        [SupplierId],
        [IDL.Vec(PurchaseOrder)],
        ['query'],
      ),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getStockHistory' : IDL.Func(
        [IDL.Opt(ProductId)],
        [IDL.Vec(StockHistoryEntry)],
        ['query'],
      ),
    'getSupplier' : IDL.Func([SupplierId], [IDL.Opt(Supplier)], ['query']),
    'getSupplierProducts' : IDL.Func(
        [SupplierId],
        [IDL.Vec(ProductId)],
        ['query'],
      ),
    'listPOs' : IDL.Func(
        [IDL.Opt(POStatus)],
        [IDL.Vec(PurchaseOrder)],
        ['query'],
      ),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listSuppliers' : IDL.Func(
        [IDL.Opt(IDL.Bool)],
        [IDL.Vec(Supplier)],
        ['query'],
      ),
    'receivePO' : IDL.Func(
        [POId, IDL.Vec(ReceiveItemArgs)],
        [IDL.Opt(PurchaseOrder)],
        [],
      ),
    'searchProducts' : IDL.Func(
        [SearchFilterArgs],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'setGlobalLowStockThreshold' : IDL.Func([IDL.Nat], [], []),
    'updatePOStatus' : IDL.Func(
        [UpdatePOStatusArgs],
        [IDL.Opt(PurchaseOrder)],
        [],
      ),
    'updateProduct' : IDL.Func(
        [UpdateProductArgs],
        [IDL.Variant({ 'ok' : Product, 'err' : IDL.Text })],
        [],
      ),
    'updateSupplier' : IDL.Func(
        [SupplierId, UpdateSupplierArgs],
        [IDL.Opt(Supplier)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };