/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CreateProductArgs {
    sku: string;
    unitOfMeasure: string;
    lowStockThreshold?: bigint;
    name: string;
    reorderQuantity: bigint;
    sellingPrice: bigint;
    description: string;
    barcode?: string;
    quantity: bigint;
    category: string;
    price: bigint;
    costPrice: bigint;
    supplierId?: SupplierId;
}
export type Timestamp = bigint;
export interface POLineItem {
    receivedQty: bigint;
    orderedQty: bigint;
    productSku: string;
    productId: ProductId;
    productName: string;
    unitCostPrice: bigint;
}
export interface CategorySummary {
    totalValue: bigint;
    productCount: bigint;
    category: string;
}
export type POId = bigint;
export interface StockHistoryEntry {
    id: bigint;
    note?: string;
    productId: ProductId;
    notes?: string;
    timestamp: Timestamp;
    quantity: bigint;
    adjustmentType: AdjustmentType;
}
export interface CreatePOArgs {
    lineItems: Array<CreatePOLineItemArgs>;
    expectedDeliveryDate?: bigint;
    supplierName: string;
    notes?: string;
    supplierId: SupplierId;
}
export interface LowStockSummary {
    id: ProductId;
    sku: string;
    reorderPoint: bigint;
    name: string;
    currentStock: bigint;
}
export interface UpdateProductArgs {
    id: ProductId;
    sku: string;
    unitOfMeasure: string;
    lowStockThreshold?: bigint;
    name: string;
    reorderQuantity: bigint;
    sellingPrice: bigint;
    description: string;
    barcode?: string;
    category: string;
    price: bigint;
    costPrice: bigint;
    supplierId?: SupplierId;
}
export interface SearchFilterArgs {
    sortField?: SortField;
    stockStatus?: StockStatus;
    sortOrder?: SortOrder;
    searchQuery?: string;
    supplierId?: SupplierId;
}
export interface UpdateSupplierArgs {
    name?: string;
    contactPerson?: string;
    isActive?: boolean;
    email?: string;
    address?: string;
    paymentTerms?: string;
    phone?: string;
}
export interface CreatePOLineItemArgs {
    orderedQty: bigint;
    productId: ProductId;
    unitCostPrice: bigint;
}
export interface ReceiveItemArgs {
    receivedQty: bigint;
    productId: ProductId;
}
export interface CreateSupplierArgs {
    name: string;
    contactPerson: string;
    isActive: boolean;
    email: string;
    address: string;
    paymentTerms: string;
    phone: string;
}
export interface AdjustStockArgs {
    note?: string;
    productId: ProductId;
    quantity: bigint;
    adjustmentType: AdjustmentType;
}
export type SupplierId = bigint;
export interface UpdatePOStatusArgs {
    id: POId;
    status: POStatus;
}
export type ProductId = bigint;
export interface Supplier {
    id: SupplierId;
    name: string;
    createdAt: Timestamp;
    contactPerson: string;
    isActive: boolean;
    email: string;
    address: string;
    paymentTerms: string;
    phone: string;
}
export interface PurchaseOrder {
    id: POId;
    status: POStatus;
    lineItems: Array<POLineItem>;
    expectedDeliveryDate?: bigint;
    supplierName: string;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    totalAmount: bigint;
    notes?: string;
    supplierId: SupplierId;
}
export interface Product {
    id: ProductId;
    sku: string;
    unitOfMeasure: string;
    lowStockThreshold?: bigint;
    stockStatus: StockStatus;
    name: string;
    reorderQuantity: bigint;
    sellingPrice: bigint;
    description: string;
    lastModified: Timestamp;
    barcode?: string;
    quantity: bigint;
    category: string;
    price: bigint;
    costPrice: bigint;
    supplierId?: SupplierId;
}
export interface DashboardMetrics {
    categories: Array<CategorySummary>;
    totalProducts: bigint;
    pendingPOValue: bigint;
    totalInventoryValue: bigint;
    pendingPOCount: bigint;
    lowStockCount: bigint;
    lowStockProducts: Array<LowStockSummary>;
}
export enum AdjustmentType {
    remove = "remove",
    return_ = "return",
    damage = "damage",
    recount = "recount",
    sale = "sale",
    receivedFromPO = "receivedFromPO",
    restock = "restock"
}
export enum POStatus {
    cancelled = "cancelled",
    sent = "sent",
    partiallyReceived = "partiallyReceived",
    draft = "draft",
    received = "received"
}
export enum SortField {
    sku = "sku",
    name = "name",
    lastModified = "lastModified",
    quantity = "quantity",
    price = "price"
}
export enum SortOrder {
    asc = "asc",
    desc = "desc"
}
export enum StockStatus {
    inStock = "inStock",
    outOfStock = "outOfStock",
    lowStock = "lowStock"
}
export interface backendInterface {
    adjustStock(args: AdjustStockArgs): Promise<{
        __kind__: "ok";
        ok: Product;
    } | {
        __kind__: "err";
        err: string;
    }>;
    cancelPO(id: POId): Promise<PurchaseOrder | null>;
    createPO(args: CreatePOArgs): Promise<PurchaseOrder>;
    createProduct(args: CreateProductArgs): Promise<{
        __kind__: "ok";
        ok: Product;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createSupplier(args: CreateSupplierArgs): Promise<Supplier>;
    deleteProduct(id: ProductId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteSupplier(id: SupplierId): Promise<boolean>;
    getDashboardMetrics(): Promise<DashboardMetrics>;
    getGlobalLowStockThreshold(): Promise<bigint>;
    getPO(id: POId): Promise<PurchaseOrder | null>;
    getPOsBySupplier(supplierId: SupplierId): Promise<Array<PurchaseOrder>>;
    getProduct(id: ProductId): Promise<Product | null>;
    getStockHistory(productId: ProductId | null): Promise<Array<StockHistoryEntry>>;
    getSupplier(id: SupplierId): Promise<Supplier | null>;
    getSupplierProducts(id: SupplierId): Promise<Array<ProductId>>;
    listPOs(statusFilter: POStatus | null): Promise<Array<PurchaseOrder>>;
    listProducts(): Promise<Array<Product>>;
    listSuppliers(isActiveFilter: boolean | null): Promise<Array<Supplier>>;
    receivePO(id: POId, receivedItems: Array<ReceiveItemArgs>): Promise<PurchaseOrder | null>;
    searchProducts(args: SearchFilterArgs): Promise<Array<Product>>;
    setGlobalLowStockThreshold(threshold: bigint): Promise<void>;
    updatePOStatus(args: UpdatePOStatusArgs): Promise<PurchaseOrder | null>;
    updateProduct(args: UpdateProductArgs): Promise<{
        __kind__: "ok";
        ok: Product;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateSupplier(id: SupplierId, args: UpdateSupplierArgs): Promise<Supplier | null>;
}
import type { AdjustStockArgs as _AdjustStockArgs, AdjustmentType as _AdjustmentType, CreatePOArgs as _CreatePOArgs, CreatePOLineItemArgs as _CreatePOLineItemArgs, CreateProductArgs as _CreateProductArgs, POId as _POId, POLineItem as _POLineItem, POStatus as _POStatus, Product as _Product, ProductId as _ProductId, PurchaseOrder as _PurchaseOrder, SearchFilterArgs as _SearchFilterArgs, SortField as _SortField, SortOrder as _SortOrder, StockHistoryEntry as _StockHistoryEntry, StockStatus as _StockStatus, Supplier as _Supplier, SupplierId as _SupplierId, Timestamp as _Timestamp, UpdatePOStatusArgs as _UpdatePOStatusArgs, UpdateProductArgs as _UpdateProductArgs, UpdateSupplierArgs as _UpdateSupplierArgs } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async adjustStock(arg0: AdjustStockArgs): Promise<{
        __kind__: "ok";
        ok: Product;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adjustStock(to_candid_AdjustStockArgs_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adjustStock(to_candid_AdjustStockArgs_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async cancelPO(arg0: POId): Promise<PurchaseOrder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelPO(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelPO(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPO(arg0: CreatePOArgs): Promise<PurchaseOrder> {
        if (this.processError) {
            try {
                const result = await this.actor.createPO(to_candid_CreatePOArgs_n19(this._uploadFile, this._downloadFile, arg0));
                return from_candid_PurchaseOrder_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPO(to_candid_CreatePOArgs_n19(this._uploadFile, this._downloadFile, arg0));
            return from_candid_PurchaseOrder_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProduct(arg0: CreateProductArgs): Promise<{
        __kind__: "ok";
        ok: Product;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(to_candid_CreateProductArgs_n21(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(to_candid_CreateProductArgs_n21(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createSupplier(arg0: CreateSupplierArgs): Promise<Supplier> {
        if (this.processError) {
            try {
                const result = await this.actor.createSupplier(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSupplier(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: ProductId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteSupplier(arg0: SupplierId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSupplier(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSupplier(arg0);
            return result;
        }
    }
    async getDashboardMetrics(): Promise<DashboardMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardMetrics();
            return result;
        }
    }
    async getGlobalLowStockThreshold(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getGlobalLowStockThreshold();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGlobalLowStockThreshold();
            return result;
        }
    }
    async getPO(arg0: POId): Promise<PurchaseOrder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPO(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPO(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPOsBySupplier(arg0: SupplierId): Promise<Array<PurchaseOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPOsBySupplier(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPOsBySupplier(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStockHistory(arg0: ProductId | null): Promise<Array<StockHistoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStockHistory(to_candid_opt_n26(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStockHistory(to_candid_opt_n26(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSupplier(arg0: SupplierId): Promise<Supplier | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSupplier(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSupplier(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSupplierProducts(arg0: SupplierId): Promise<Array<ProductId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSupplierProducts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSupplierProducts(arg0);
            return result;
        }
    }
    async listPOs(arg0: POStatus | null): Promise<Array<PurchaseOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPOs(to_candid_opt_n33(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPOs(to_candid_opt_n33(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSuppliers(arg0: boolean | null): Promise<Array<Supplier>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSuppliers(to_candid_opt_n37(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSuppliers(to_candid_opt_n37(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async receivePO(arg0: POId, arg1: Array<ReceiveItemArgs>): Promise<PurchaseOrder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.receivePO(arg0, arg1);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.receivePO(arg0, arg1);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchProducts(arg0: SearchFilterArgs): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProducts(to_candid_SearchFilterArgs_n38(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProducts(to_candid_SearchFilterArgs_n38(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async setGlobalLowStockThreshold(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setGlobalLowStockThreshold(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setGlobalLowStockThreshold(arg0);
            return result;
        }
    }
    async updatePOStatus(arg0: UpdatePOStatusArgs): Promise<PurchaseOrder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePOStatus(to_candid_UpdatePOStatusArgs_n46(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePOStatus(to_candid_UpdatePOStatusArgs_n46(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProduct(arg0: UpdateProductArgs): Promise<{
        __kind__: "ok";
        ok: Product;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(to_candid_UpdateProductArgs_n48(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(to_candid_UpdateProductArgs_n48(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSupplier(arg0: SupplierId, arg1: UpdateSupplierArgs): Promise<Supplier | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSupplier(arg0, to_candid_UpdateSupplierArgs_n50(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSupplier(arg0, to_candid_UpdateSupplierArgs_n50(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AdjustmentType_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdjustmentType): AdjustmentType {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_POStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _POStatus): POStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PurchaseOrder_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PurchaseOrder): PurchaseOrder {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_StockHistoryEntry_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StockHistoryEntry): StockHistoryEntry {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_StockStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StockStatus): StockStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SupplierId]): SupplierId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PurchaseOrder]): PurchaseOrder | null {
    return value.length === 0 ? null : from_candid_PurchaseOrder_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Supplier]): Supplier | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _POId;
    status: _POStatus;
    lineItems: Array<_POLineItem>;
    expectedDeliveryDate: [] | [bigint];
    supplierName: string;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    totalAmount: bigint;
    notes: [] | [string];
    supplierId: _SupplierId;
}): {
    id: POId;
    status: POStatus;
    lineItems: Array<POLineItem>;
    expectedDeliveryDate?: bigint;
    supplierName: string;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    totalAmount: bigint;
    notes?: string;
    supplierId: SupplierId;
} {
    return {
        id: value.id,
        status: from_candid_POStatus_n16(_uploadFile, _downloadFile, value.status),
        lineItems: value.lineItems,
        expectedDeliveryDate: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.expectedDeliveryDate)),
        supplierName: value.supplierName,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        totalAmount: value.totalAmount,
        notes: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.notes)),
        supplierId: value.supplierId
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    note: [] | [string];
    productId: _ProductId;
    notes: [] | [string];
    timestamp: _Timestamp;
    quantity: bigint;
    adjustmentType: _AdjustmentType;
}): {
    id: bigint;
    note?: string;
    productId: ProductId;
    notes?: string;
    timestamp: Timestamp;
    quantity: bigint;
    adjustmentType: AdjustmentType;
} {
    return {
        id: value.id,
        note: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.note)),
        productId: value.productId,
        notes: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.notes)),
        timestamp: value.timestamp,
        quantity: value.quantity,
        adjustmentType: from_candid_AdjustmentType_n30(_uploadFile, _downloadFile, value.adjustmentType)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProductId;
    sku: string;
    unitOfMeasure: string;
    lowStockThreshold: [] | [bigint];
    stockStatus: _StockStatus;
    name: string;
    reorderQuantity: bigint;
    sellingPrice: bigint;
    description: string;
    lastModified: _Timestamp;
    barcode: [] | [string];
    quantity: bigint;
    category: string;
    price: bigint;
    costPrice: bigint;
    supplierId: [] | [_SupplierId];
}): {
    id: ProductId;
    sku: string;
    unitOfMeasure: string;
    lowStockThreshold?: bigint;
    stockStatus: StockStatus;
    name: string;
    reorderQuantity: bigint;
    sellingPrice: bigint;
    description: string;
    lastModified: Timestamp;
    barcode?: string;
    quantity: bigint;
    category: string;
    price: bigint;
    costPrice: bigint;
    supplierId?: SupplierId;
} {
    return {
        id: value.id,
        sku: value.sku,
        unitOfMeasure: value.unitOfMeasure,
        lowStockThreshold: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.lowStockThreshold)),
        stockStatus: from_candid_StockStatus_n9(_uploadFile, _downloadFile, value.stockStatus),
        name: value.name,
        reorderQuantity: value.reorderQuantity,
        sellingPrice: value.sellingPrice,
        description: value.description,
        lastModified: value.lastModified,
        barcode: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.barcode)),
        quantity: value.quantity,
        category: value.category,
        price: value.price,
        costPrice: value.costPrice,
        supplierId: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.supplierId))
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inStock: null;
} | {
    outOfStock: null;
} | {
    lowStock: null;
}): StockStatus {
    return "inStock" in value ? StockStatus.inStock : "outOfStock" in value ? StockStatus.outOfStock : "lowStock" in value ? StockStatus.lowStock : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    sent: null;
} | {
    partiallyReceived: null;
} | {
    draft: null;
} | {
    received: null;
}): POStatus {
    return "cancelled" in value ? POStatus.cancelled : "sent" in value ? POStatus.sent : "partiallyReceived" in value ? POStatus.partiallyReceived : "draft" in value ? POStatus.draft : "received" in value ? POStatus.received : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    remove: null;
} | {
    return: null;
} | {
    damage: null;
} | {
    recount: null;
} | {
    sale: null;
} | {
    receivedFromPO: null;
} | {
    restock: null;
}): AdjustmentType {
    return "remove" in value ? AdjustmentType.remove : "return" in value ? AdjustmentType.return : "damage" in value ? AdjustmentType.damage : "recount" in value ? AdjustmentType.recount : "sale" in value ? AdjustmentType.sale : "receivedFromPO" in value ? AdjustmentType.receivedFromPO : "restock" in value ? AdjustmentType.restock : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Product;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Product;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Product_n6(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PurchaseOrder>): Array<PurchaseOrder> {
    return value.map((x)=>from_candid_PurchaseOrder_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StockHistoryEntry>): Array<StockHistoryEntry> {
    return value.map((x)=>from_candid_StockHistoryEntry_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n6(_uploadFile, _downloadFile, x));
}
function to_candid_AdjustStockArgs_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdjustStockArgs): _AdjustStockArgs {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_AdjustmentType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdjustmentType): _AdjustmentType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_CreatePOArgs_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreatePOArgs): _CreatePOArgs {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_CreateProductArgs_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateProductArgs): _CreateProductArgs {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_POStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: POStatus): _POStatus {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_SearchFilterArgs_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SearchFilterArgs): _SearchFilterArgs {
    return to_candid_record_n39(_uploadFile, _downloadFile, value);
}
function to_candid_SortField_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortField): _SortField {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_SortOrder_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortOrder): _SortOrder {
    return to_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function to_candid_StockStatus_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StockStatus): _StockStatus {
    return to_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function to_candid_UpdatePOStatusArgs_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdatePOStatusArgs): _UpdatePOStatusArgs {
    return to_candid_record_n47(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateProductArgs_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateProductArgs): _UpdateProductArgs {
    return to_candid_record_n49(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateSupplierArgs_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateSupplierArgs): _UpdateSupplierArgs {
    return to_candid_record_n51(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductId | null): [] | [_ProductId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: POStatus | null): [] | [_POStatus] {
    return value === null ? candid_none() : candid_some(to_candid_POStatus_n34(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: boolean | null): [] | [boolean] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    note?: string;
    productId: ProductId;
    quantity: bigint;
    adjustmentType: AdjustmentType;
}): {
    note: [] | [string];
    productId: _ProductId;
    quantity: bigint;
    adjustmentType: _AdjustmentType;
} {
    return {
        note: value.note ? candid_some(value.note) : candid_none(),
        productId: value.productId,
        quantity: value.quantity,
        adjustmentType: to_candid_AdjustmentType_n3(_uploadFile, _downloadFile, value.adjustmentType)
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lineItems: Array<CreatePOLineItemArgs>;
    expectedDeliveryDate?: bigint;
    supplierName: string;
    notes?: string;
    supplierId: SupplierId;
}): {
    lineItems: Array<_CreatePOLineItemArgs>;
    expectedDeliveryDate: [] | [bigint];
    supplierName: string;
    notes: [] | [string];
    supplierId: _SupplierId;
} {
    return {
        lineItems: value.lineItems,
        expectedDeliveryDate: value.expectedDeliveryDate ? candid_some(value.expectedDeliveryDate) : candid_none(),
        supplierName: value.supplierName,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        supplierId: value.supplierId
    };
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sku: string;
    unitOfMeasure: string;
    lowStockThreshold?: bigint;
    name: string;
    reorderQuantity: bigint;
    sellingPrice: bigint;
    description: string;
    barcode?: string;
    quantity: bigint;
    category: string;
    price: bigint;
    costPrice: bigint;
    supplierId?: SupplierId;
}): {
    sku: string;
    unitOfMeasure: string;
    lowStockThreshold: [] | [bigint];
    name: string;
    reorderQuantity: bigint;
    sellingPrice: bigint;
    description: string;
    barcode: [] | [string];
    quantity: bigint;
    category: string;
    price: bigint;
    costPrice: bigint;
    supplierId: [] | [_SupplierId];
} {
    return {
        sku: value.sku,
        unitOfMeasure: value.unitOfMeasure,
        lowStockThreshold: value.lowStockThreshold ? candid_some(value.lowStockThreshold) : candid_none(),
        name: value.name,
        reorderQuantity: value.reorderQuantity,
        sellingPrice: value.sellingPrice,
        description: value.description,
        barcode: value.barcode ? candid_some(value.barcode) : candid_none(),
        quantity: value.quantity,
        category: value.category,
        price: value.price,
        costPrice: value.costPrice,
        supplierId: value.supplierId ? candid_some(value.supplierId) : candid_none()
    };
}
function to_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sortField?: SortField;
    stockStatus?: StockStatus;
    sortOrder?: SortOrder;
    searchQuery?: string;
    supplierId?: SupplierId;
}): {
    sortField: [] | [_SortField];
    stockStatus: [] | [_StockStatus];
    sortOrder: [] | [_SortOrder];
    searchQuery: [] | [string];
    supplierId: [] | [_SupplierId];
} {
    return {
        sortField: value.sortField ? candid_some(to_candid_SortField_n40(_uploadFile, _downloadFile, value.sortField)) : candid_none(),
        stockStatus: value.stockStatus ? candid_some(to_candid_StockStatus_n42(_uploadFile, _downloadFile, value.stockStatus)) : candid_none(),
        sortOrder: value.sortOrder ? candid_some(to_candid_SortOrder_n44(_uploadFile, _downloadFile, value.sortOrder)) : candid_none(),
        searchQuery: value.searchQuery ? candid_some(value.searchQuery) : candid_none(),
        supplierId: value.supplierId ? candid_some(value.supplierId) : candid_none()
    };
}
function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: POId;
    status: POStatus;
}): {
    id: _POId;
    status: _POStatus;
} {
    return {
        id: value.id,
        status: to_candid_POStatus_n34(_uploadFile, _downloadFile, value.status)
    };
}
function to_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ProductId;
    sku: string;
    unitOfMeasure: string;
    lowStockThreshold?: bigint;
    name: string;
    reorderQuantity: bigint;
    sellingPrice: bigint;
    description: string;
    barcode?: string;
    category: string;
    price: bigint;
    costPrice: bigint;
    supplierId?: SupplierId;
}): {
    id: _ProductId;
    sku: string;
    unitOfMeasure: string;
    lowStockThreshold: [] | [bigint];
    name: string;
    reorderQuantity: bigint;
    sellingPrice: bigint;
    description: string;
    barcode: [] | [string];
    category: string;
    price: bigint;
    costPrice: bigint;
    supplierId: [] | [_SupplierId];
} {
    return {
        id: value.id,
        sku: value.sku,
        unitOfMeasure: value.unitOfMeasure,
        lowStockThreshold: value.lowStockThreshold ? candid_some(value.lowStockThreshold) : candid_none(),
        name: value.name,
        reorderQuantity: value.reorderQuantity,
        sellingPrice: value.sellingPrice,
        description: value.description,
        barcode: value.barcode ? candid_some(value.barcode) : candid_none(),
        category: value.category,
        price: value.price,
        costPrice: value.costPrice,
        supplierId: value.supplierId ? candid_some(value.supplierId) : candid_none()
    };
}
function to_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name?: string;
    contactPerson?: string;
    isActive?: boolean;
    email?: string;
    address?: string;
    paymentTerms?: string;
    phone?: string;
}): {
    name: [] | [string];
    contactPerson: [] | [string];
    isActive: [] | [boolean];
    email: [] | [string];
    address: [] | [string];
    paymentTerms: [] | [string];
    phone: [] | [string];
} {
    return {
        name: value.name ? candid_some(value.name) : candid_none(),
        contactPerson: value.contactPerson ? candid_some(value.contactPerson) : candid_none(),
        isActive: value.isActive ? candid_some(value.isActive) : candid_none(),
        email: value.email ? candid_some(value.email) : candid_none(),
        address: value.address ? candid_some(value.address) : candid_none(),
        paymentTerms: value.paymentTerms ? candid_some(value.paymentTerms) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: POStatus): {
    cancelled: null;
} | {
    sent: null;
} | {
    partiallyReceived: null;
} | {
    draft: null;
} | {
    received: null;
} {
    return value == POStatus.cancelled ? {
        cancelled: null
    } : value == POStatus.sent ? {
        sent: null
    } : value == POStatus.partiallyReceived ? {
        partiallyReceived: null
    } : value == POStatus.draft ? {
        draft: null
    } : value == POStatus.received ? {
        received: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdjustmentType): {
    remove: null;
} | {
    return: null;
} | {
    damage: null;
} | {
    recount: null;
} | {
    sale: null;
} | {
    receivedFromPO: null;
} | {
    restock: null;
} {
    return value == AdjustmentType.remove ? {
        remove: null
    } : value == AdjustmentType.return ? {
        return_: null
    } : value == AdjustmentType.damage ? {
        damage: null
    } : value == AdjustmentType.recount ? {
        recount: null
    } : value == AdjustmentType.sale ? {
        sale: null
    } : value == AdjustmentType.receivedFromPO ? {
        receivedFromPO: null
    } : value == AdjustmentType.restock ? {
        restock: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortField): {
    sku: null;
} | {
    name: null;
} | {
    lastModified: null;
} | {
    quantity: null;
} | {
    price: null;
} {
    return value == SortField.sku ? {
        sku: null
    } : value == SortField.name ? {
        name: null
    } : value == SortField.lastModified ? {
        lastModified: null
    } : value == SortField.quantity ? {
        quantity: null
    } : value == SortField.price ? {
        price: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StockStatus): {
    inStock: null;
} | {
    outOfStock: null;
} | {
    lowStock: null;
} {
    return value == StockStatus.inStock ? {
        inStock: null
    } : value == StockStatus.outOfStock ? {
        outOfStock: null
    } : value == StockStatus.lowStock ? {
        lowStock: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortOrder): {
    asc: null;
} | {
    desc: null;
} {
    return value == SortOrder.asc ? {
        asc: null
    } : value == SortOrder.desc ? {
        desc: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
